Remove unnecessary punctuation and tidy up
Punctuation only really serves to confound any scripts checking the
output and limits (or frustrates) other potential computation.

Also fixes some logic, such as using an array simply to provide an error
message which wasn't necessary as the last value can simply be used.
The semantics are already documented.

diff --git a/barkeep b/barkeep
--- a/barkeep
+++ b/barkeep
@@ -1,17 +1,16 @@
 #!/usr/bin/env bash
 # barkeep
-# Creates a game entry based on a template for use with `taverner`
+# Creates a game entry based on a template for use with `taverner`.
 
 # Options
 shopt -s nullglob
 
-# Globals
-readonly progn=barkeep
-readonly datadir="${XDG_DATA_HOME:-$HOME/.local/share}"
-readonly prefix="$datadir"/taverner
-readonly bindir="$prefix"/bin
-readonly coverdir="$prefix"/covers
-readonly templatedir="$prefix"/templates
+readonly argv0=barkeep
+
+readonly prefix=${XDG_DATA_HOME:-$HOME/.local/share}/taverner
+readonly bindir=$prefix/bin
+readonly coverdir=$prefix/covers
+readonly templatedir=$prefix/templates
 
 readonly TMPDIR=/tmp
 
@@ -98,17 +97,17 @@ puts() {
 }
 
 err() {
-    puts "$progn: $@" >&2
+    puts "$argv0: $1" "${@:2}" >&2
 }
 
 confirm() {
     local msg=$1
     local -l reply
 
-    read -p "$msg [Y/n] " reply
+    read -rp "$msg [Y/n] " reply
 
     # If the reply is empty, assume Y
-    [[ $reply = y || ! $reply ]]
+    [[ $reply == y || ! $reply ]]
 }
 
 handle_ls() {
@@ -116,8 +115,7 @@ handle_ls() {
         case $1 in
             -t) ls_templates; exit ;;
             -h) usage_ls; exit ;;
-            *)  err '%s: Unrecognised argument.' "$1"
-                usage_ls; exit 1 ;;
+            *)  err '%s: Unrecognised argument' "$1"; exit 1 ;;
         esac
         shift
     done
@@ -133,7 +131,7 @@ ls_entries() {
     if ((${#entries[@]})); then
         puts '%s' "${entries[@]##*/}"
     else
-        err '%s: No entries found here.' "$bindir"
+        err '%s: No entries found here' "$bindir"
     fi
 }
 
@@ -145,7 +143,7 @@ ls_templates() {
     if ((${#templates[@]})); then
         puts '%s' "${templates[@]##*/}"
     else
-        err '%s: No templates found here.' "$templatedir"
+        err '%s: No templates found here' "$templatedir"
     fi
 }
 
@@ -163,25 +161,23 @@ handle_mk() {
         shift
     done
 
-    if [[ !$entry ]]; then
-        err 'An entry name is required.'
-        usage_mk
+    if [[ ! $entry ]]; then
+        err 'An entry name is required'
         exit 1
     fi
 
     if [[ -e $bindir/$entry ]]; then
-        err '%s: This entry already exists.  See `%s ls -e`.' "$bindir"/"$entry" "$progn"
+        err '%s: This entry already exists.  See %s ls -e' "$bindir"/"$entry" "$argv0"
         exit 1
     fi
 
     if [[ ! $template ]]; then
-        err 'A template required.  See `%s ls -t`.' "$progn"
-        usage_mk
+        err 'A template required.  See %s ls -t' "$argv0"
         exit 1
     fi
 
     if [[ ! -e $templatedir/$template ]]; then
-        err '%s: Unable to find requested template.' "$templatedir"/"$template"
+        err '%s: Unable to find requested template' "$templatedir"/"$template"
         exit 1
     fi
 
@@ -212,7 +208,7 @@ mk_cover() {
         if curl -#o "$TMPDIR"/barkeep_cover "$cover"; then
             cover=$TMPDIR/barkeep_cover
         else
-            err '%s: Failed to download cover.' "$cover"
+            err '%s: Failed to download cover' "$cover"
             exit 1
         fi
     fi
@@ -221,7 +217,7 @@ mk_cover() {
         command gm mogrify -resize 368x527\! "$cover"
         mv -vf -- "$cover" "$coverdir"/"$entry"
     else
-        err '%s: Unable to find cover.' "$cover"
+        err '%s: Unable to find cover' "$cover"
     fi
 }
 
@@ -245,7 +241,7 @@ handle_rm() {
         entries=(${entries[@]##$bindir/})
 
         if ! ((${#entries[@]})); then
-            err '%s: Nothing here to remove.' "$bindir"
+            err '%s: Nothing here to remove' "$bindir"
             exit 1
         fi
     fi
@@ -254,7 +250,7 @@ handle_rm() {
     puts '%s' "${entries[@]##$bindir/}"
 
     if ! confirm 'Continue?'; then
-        puts 'Nothing removed.'
+        puts 'Nothing removed'
         exit
     fi
 
@@ -280,15 +276,10 @@ handle_ed() {
             -t) shift; template=$1 ;;
             -e) shift; editor=$1 ;;
             -h) usage_ed; exit ;;
-            *) entry=($1)
+            *) entry=$1
         esac
         shift
     done
-
-    if ((${#entry[@]} > 1)); then
-        err 'Only one entry can be edited per innvocation.'
-        exit 1
-    fi
 
     if [[ $entry && $cover ]]; then
         mk_cover "$entry" "$cover"
@@ -308,10 +299,10 @@ handle_ed() {
     fi
 }
 
-mkdir -p "$datadir" "$bindir" "$coverdir" "$templatedir"
+mkdir -p "$bindir" "$coverdir" "$templatedir"
 
 if ! (($#)); then
-    err 'At least one argument is required.'
+    err 'At least one argument is required'
     usage
     exit 1
 fi
@@ -328,7 +319,7 @@ while (($#)); do
             exit ;;
         -h) usage
             exit ;;
-        *)  err '%s: Unrecognised argument.' "$1"
+        *)  err '%s: Unrecognised argument' "$1"
             usage
             exit 1
     esac
diff --git a/taverner b/taverner
--- a/taverner
+++ b/taverner
@@ -5,15 +5,11 @@
 
 shopt -s nullglob
 
-readonly progn=taverner
-readonly datadir=${XDG_DATA_HOME:-$HOME/.local/share}
-readonly prefix=$datadir/taverner
+readonly argv0=taverner
+
+readonly prefix=${XDG_DATA_HOME:-$HOME/.local/share}/taverner
 readonly bindir=$prefix/bin
 readonly coverdir=$prefix/covers
-
-# Main globals used throughout the code, unfortunately.
-declare -A titles
-declare -A covers
 
 read -r font < "${XDG_CONFIG_HOME:-$HOME/.config}"/dmenu/font
 readonly dmenu_opts=(
@@ -28,7 +24,7 @@ puts() {
 }
 
 err() {
-    puts "$progn: $@" >&2
+    puts "$argv0: $1" "${@:2}" >&2
 }
 
 title_in() {
@@ -71,16 +67,17 @@ generate_entry_data() {
     done
 }
 
-create_menu() {
+create_sorted_menu() {
+    # global titles covers
     local key
 
     for key in "${!titles[@]}"; do
         puts 'IMG:%s\t%s' "${covers[$key]}" "$key"
-    done
+    done | sort
 }
 
 get_user_picks() {
-    create_menu | sort | dmenu "${dmenu_opts[@]}"
+    create_sorted_menu | dmenu "${dmenu_opts[@]}"
 }
 
 launch() {
@@ -93,10 +90,10 @@ launch() {
 }
 
 populate_arrays() {
-    #global titles covers
+    # global titles covers entry
 
-    # Parse the list into two arrays.  We keep a consistent key so we can access
-    # the correct corresonding information for both lookups.
+    # Parse the list into two arrays.  We keep a consistent key so we can
+    # access the correct corresonding information for both lookups.
     while {
         read -r title
         read -r entry
@@ -108,14 +105,14 @@ populate_arrays() {
 }
 
 process_results() {
-    #global titles
+    # global titles
     local pick entry
 
     while read -r pick; do
-        if [[ -n "${titles[$pick]}" ]]; then
+        if [[ ${titles[$pick]} ]]; then
             entry="${titles[$pick]}"
         else
-            err '%s: Cannot find associated launcher.' "$pick"
+            err '%s: Cannot find associated launcher' "$pick"
             exit 1
         fi
 
@@ -123,7 +120,10 @@ process_results() {
     done
 }
 
-mkdir -p "$datadir" "$bindir" "$coverdir"
+declare -A titles
+declare -A covers
+
+mkdir -p "$bindir" "$coverdir"
 
 populate_arrays < <(generate_entry_data)
 
