Rewrite taverner and barkeep, remove libtavern.

diff --git a/barkeep b/barkeep
--- a/barkeep
+++ b/barkeep
@@ -2,273 +2,278 @@
 # barkeep
 # Creates a game entry based on a template for use with `taverner`
 
-# Includes get_abs_dir, in_array, chk_exists_dir, confirm, err, warn, debug, msg
-if ! source "$HOME"/.local/lib/libtavern; then
-    printf >&2 '[ERR] Failed to source %s\n' "$HOME"/.local/lib/libtavern
-    exit 1
-fi
-
 # Options
 shopt -s nullglob
 
 # Globals
 prefix="$HOME"/games
-bindir="$prefix"/bin
-cachedir="$prefix"/share/cache
-coverdir="$prefix"/share/covers
-templatedir="$prefix"/share/templates
-placeholder="$prefix"/share/covers/placeholder.cover
+readonly progn=barkeep
+readonly datadir="${XDG_DATA_HOME:-$HOME/.local/share}"
+readonly prefix="$datadir"/taverner
+readonly bindir="$prefix"/bin
+readonly coverdir="$prefix"/covers
+readonly templatedir="$prefix"/templates
 
-TMPDIR=/tmp # Used for internet incoming images
+readonly TMPDIR=/tmp
 
-# Check that the directories actually exist before attempting anything
-dirs_exist "$prefix" "$bindir" "$coverdir" "$cachedir" "$templatedir" "$TMPDIR"
-
-
-# Functions and helpers
-usage() {
+usage_mk() {
     cat <<EOF
-Usage: barkeep -n <name> -t <template> [-c <cover>] [-e <editor>] [-l]
-       barkeep -r [name [name [...]]]
-
-    Operations:
-        -l      List all available templates
-        -n      Name of the new game launcher script
-        -t      Select a template to base the new entry on
-        -c      Path or url to a cover image (note: this is destructive)
-        -e      Prefered editor, uses \$EDITOR if not set
-
-    Single Operations:
-        -r      Remove launcher(s), cover(s) and reset database
-                If no argument given, attempt to remove all launchers
-
-    Examples:
-        # Creates an entry using the psx template called wipeout_3 using emacs
-        # as the editor
-        barkeep -e emacs -n wipeout_3 -t psx -c ~/wipeout.png
-        
-        # Removes both wipeout_3 and crash_bandicoot launchers along with any
-        # cover images if found and resets the cache
-        barkeep -r wipeout_3 crash_bandicoot
+    mk <name> -t <template> [-c <cover>] [-e <editor>]
+        -t      Select a template to base the new entry on.
+        -c      Path or url to a cover image (note: this is destructive).
+        -e      Prefered editor, uses \$EDITOR if not set.
+        name    The name for the new launcher script.
 
 EOF
 }
 
-chk_template() {
-    local name="$1"
-    local t list
-    
-    for t in "$templatedir"/*; do
-        list+=("${t##*/}")
-    done
+usage_ls() {
+    cat <<EOF
+    ls [-t]
+        -t      List all available templates.
 
-    # Generate a list for `barkeep -l`
-    if [[ "$name" == list && -n "${t[@]}" ]]; then
-        printf '%03s\n' "${list[@]}"
-        exit 0
-    # If we found no templates at all
-    elif [[ -z "${list[@]}" ]]; then
-        err "No templates available"
-        exit 1
-    # Then make sure the chosen template exists itself
-    elif ! in_array "$name" "${list[@]}"; then
-        err "$template: No such template"
-        exit 1
-    fi
+        If no arguments given this will list all entries.
+
+EOF
 }
 
-resize_cover() {
-    local image="$1"
+usage_rm() {
+    cat <<EOF
+    rm [name [name]]
+        Remove launcher(s) and cover(s).
+        If no argument given, attempt to remove all launchers.
 
-    if [[ -e "$image" ]]; then
-        command convert "$image" -resize 368x527\! "$image"
-    fi
+EOF
 }
 
-rm_launcher() {
-    local names
-    local n coverimg
+usage() {
+    cat <<EOF
+Usage: barkeep [-h] mk | rm | ls
+    Each mode has a -h flag which produces a summary of its help section.
 
-    if [[ -n "$@" ]]; then
-        names=("$@")
+EOF
+
+usage_mk
+usage_ls
+usage_rm
+
+    cat <<EOF
+Examples:
+    # Creates an entry using the psx template called wipeout_3 using emacs
+    # as the editor.
+    barkeep mk -e emacs -t psx -c ~/wipeout.png wipeout_3
+
+    # Removes both wipeout_3 and crash_bandicoot launchers along with any
+    # cover images if found.
+    barkeep rm wipeout_3 crash_bandicoot
+
+EOF
+}
+
+puts() {
+    printf -- "$1\n" "${@:2}"
+}
+
+err() {
+    puts "$progn: $@" >&2
+}
+
+confirm() {
+    local msg="$1"
+    local -l reply
+
+    read -p "$msg [Y/n] " reply
+
+    # If the reply is empty, assume Y
+    if [[ -z "$reply" || "$reply" = y?(es) ]]; then
+        return 0
     else
-        # If we get no arguments, just add everything we can find in the bindir
-        names=("$bindir"/*)
+        return 1
     fi
-
-    for n in "${names[@]}"; do
-        coverimg="$coverdir"/"${n##*/}".cover
-
-        # If the file doesn't actually exist, skip it instead of failing
-        if [[ ! -e "$bindir"/"${n##*/}" ]]; then
-            warn "$bindir/${n##*/}: No such file, skipping"
-        elif confirm "Remove $bindir/${n##*/}?"; then
-            rm -vf -- "$bindir"/"${n##*/}"
-            rm -vf -- "$cachedir"/cache.db
-
-            # Make sure a cover image exists before trying to remove it
-            if [[ -e "$coverimg" ]]; then
-                rm -vf -- "$coverdir"/"${n##*/}".cover
-            fi
-        fi
-    done
 }
 
-mk_template() {
-    local name="$1"
+handle_ls() {
+    while (($#)); do
+        case $1 in
+            -t) ls_templates; exit ;;
+            -h) usage_ls; exit ;;
+            *)  err '%s: Unrecognised argument.' "$1"
+                usage_ls; exit 1 ;;
+        esac
+        shift
+    done
+    ls_entries
+}
+
+ls_entries() {
+    #global bindir
+    local entries
+
+    entries=("$bindir"/*)
+
+    if [[ -n "$entries" ]]; then
+        puts 'Current entries:'
+        puts '    %s' "${entries[@]##*/}"
+        puts ""
+    else
+        err '%s: No entries found.' "$entries"
+    fi
+}
+
+ls_templates() {
+    #global templatedir
+    local templates
+
+    templates=("$templatedir"/*)
+
+    if [[ -n "$templates" ]]; then
+        puts 'Available templates:'
+        puts '    %s' "${templates[@]##*/}"
+        puts ""
+    else
+        err '%s: No templates found.' "$templatedir"
+    fi
+}
+
+handle_mk() {
+    #global bindir templatedir coverdir EDITOR
+    local entry cover template editor
+
+    while (($#)); do
+        case $1 in
+            -c) shift; cover="$1" ;;
+            -t) shift; template="$1" ;;
+            -e) shift; editor="$1" ;;
+            -h) usage_mk; exit ;;
+            *) entry="$1"
+        esac
+        shift
+    done
+
+    if [[ -z "$entry" ]]; then
+        err 'An entry name is required.'
+        usage_mk
+        exit 1
+    fi
+
+    if [[ -e "$bindir"/"$entry" ]]; then
+        err '%s: This entry already exists.  See `%s ls -e`.' "$bindir"/"$entry" "$progn"
+        exit 1
+    fi
+
+    if [[ -z "$template" ]]; then
+        err 'A template required.  See `%s ls -t`.' "$progn"
+        usage_mk
+        exit 1
+    fi
+
+    if [[ ! -e "$templatedir"/"$template" ]]; then
+        err '%s: Unable to find requested template.' "$templatedir"/"$template"
+        exit 1
+    fi
+
+    if [[ -z "$cover" ]]; then
+        cover="$coverdir"/placeholder
+    else
+        mk_cover "$entry" "$cover"
+    fi
+
+    mk_entry "$bindir"/"$entry" "$templatedir"/"$template"
+}
+
+mk_entry() {
+    local entry="$1"
     local template="$2"
 
-    # Check the template and make sure it doesn't already exist and is available
-    chk_template "$template"
-
-    if [[ -e "$bindir"/"$name" ]]; then
-        err "$bindir/$name: Already exists"
-        exit 1
-    else
-        cp -v -- "$templatedir"/"$template" "$bindir"/"$name"
-        chmod -c +x -- "$bindir"/"$name"
-    fi
+    cp -v -- "$template" "$entry"
+    command "${editor:-${EDITOR:-vi}}" "$entry"
+    chmod +x -- "$entry"
 }
 
 mk_cover() {
-    local name="$1"
+    local entry="$1"
     local cover="$2"
-    local coverpath
 
-    # Lets check that the placeholder actually exists here so warnings don't
-    # appear when removing titles that have nothing to do with the placeholder
-    if [[ ! -e "$placeholder" ]]; then
-        warn "$placeholder: Not found, using nothing instead"
-        placeholder="nothing"
-    fi
-
-    # Support http, https and ftp 
-    if [[ "$cover" =~ [ht\|f]tps? ]]; then
-        if curl -o "$TMPDIR"/barkeep-image "$cover"; then
-            coverpath="$TMPDIR"/barkeep-image
+    if [[ "$cover" =~ [https?\|f]tp ]]; then
+        if curl -#o "$TMPDIR"/barkeep_cover "$cover"; then
+            cover="$TMPDIR"/barkeep_cover
         else
-            warn "Failed to fetch $cover"
+            err '%s: Failed to download cover.' "$cover"
+            exit 1
         fi
+    fi
+
+    if [[ -e "$cover" ]]; then
+        command convert "$cover" -resize 368x527\! "$cover"
+        mv -v -- "$cover" "$coverdir"/"$entry"
     else
-        # Get the absolute path to the cover image 
-        coverpath="$(get_abs_dir "$cover")"
-    fi
-
-    if [[ ! -e "$coverpath" ]]; then
-        warn "No cover image available, using $placeholder"
-    fi
-
-    if [[ -e "$coverdir"/"$name" ]]; then
-        warn "$coverdir/$name: Already exists, using $coverdir/$name.cover"
-    elif [[ -e "$coverpath" ]]; then
-        mv -v -- "$coverpath" "$coverdir"/"$name".cover
-        if ! resize_cover "$coverdir"/"$name".cover; then
-            warn "Failed to resize image, falling back to $placeholder"
-            rm -vf -- "$coverdir"/"$name".cover
-        fi
+        err '%s: I lost the cover image :-(.' "$cover"
     fi
 }
 
-# We need at least one argument, if none are provided display usage information
-# and exit
+handle_rm() {
+    local entry entries remove
+
+    while (($#)); do
+        case $1 in
+            -h) usage_rm; exit ;;
+            *)  entries+=("$1")
+        esac
+        shift
+    done
+
+    if [[ -z "${entries[@]}" ]]; then
+        entries=("$bindir"/*)
+        entries="${entries[@]##$bindir/}"
+
+        if [[ -z "${entries[@]}" ]]; then
+            err '%s: Nothing here to remove.' "$bindir"
+            exit 1
+        fi
+    fi
+
+    puts 'Attempting to remove the following launchers:'
+    puts '%s' "${entries[@]}"
+
+    if ! confirm "Continue?"; then
+        puts 'Nothing removed.'
+        exit
+    fi
+
+    for entry in "${entries[@]}"; do
+        if [[ -e "$bindir"/"$entry" ]]; then
+            remove+=("$bindir"/"$entry")
+        fi
+
+        if [[ -e "$coverdir"/"$entry" ]]; then
+            remove+=("$coverdir"/"$entry")
+        fi
+    done
+
+    rm -v -- "${remove[@]}"
+}
+
+mkdir -p "$datadir" "$bindir" "$coverdir"
+
 if (($# == 0)); then
-    err "At least one argument is required"
+    err 'At least one argument is required.'
     usage
     exit 1
 fi
 
-# I will handle the errors manually
-while getopts ':hlt:d:c:n:re:' argv; do
-    case "$argv" in
-        n)
-            name="$OPTARG"
-
-            # The following is a hack to work around multiple arguments given to 
-            # a single option, this will use current OPTIND as the index to $@
-            # plus one argument, then if it doesn't begin with a '-', increment
-            # it, skipping extra non-arguments until we fine one.
-            
-            # This allows us to restrict an option to only accept a single 
-            # argument.
-            [[ "${@:OPTIND:1}" != -* ]] && ((++OPTIND))
-            ;;
-        t)
-            template="$OPTARG"
-            [[ "${@:OPTIND:1}" != -* ]] && ((++OPTIND))
-            ;;
-        e)
-            editor="$OPTARG"
-            [[ "${@:OPTIND:1}" != -* ]] && ((++OPTIND))
-            ;;
-        c)
-            cover="$OPTARG"
-            [[ "${@:OPTIND:1}" != -* ]] && ((++OPTIND))
-            ;;
-        r)
-            remove=t
-            shift
-            ;;
-        l)
-            chk_template list
-            ;;
-        h)
-            usage
-            exit 0
-            ;;
-        :)
-            err "Option -$OPTARG requires an argument"
+while (($#)); do
+    case $1 in
+        ls) shift; handle_ls "$@"
+            exit ;;
+        mk) shift; handle_mk "$@"
+            exit ;;
+        rm) shift; handle_rm "$@"
+            exit ;;
+        -h) usage
+            exit ;;
+        *)  err '%s: Unrecognised argument.' "$1"
             usage
             exit 1
-            ;;
-        ?)
-            err "Invalid option: -$OPTARG"
-            usage
-            exit 1
-            ;;
     esac
+    shift
 done
-
-# Process removal before continuing making sure that both of the mandatory
-# arguments aren't set before attempting it
-if [[ "$remove" == t && -z "$name" && -z "$template" ]]; then
-    rm_launcher "$@"
-    exit 0
-fi
-
-# Make sure a name is supplied
-if [[ -z "$name" ]]; then
-    err "A NAME is required"
-    exit 1
-fi
-
-# Set the editor if none was specified
-if [[ -z "$editor" ]]; then
-    EDITOR="${VISUAL:-$EDITOR}"
-else
-    EDITOR="$editor"
-fi
-
-# Exit before making a template as an editor is required, otherwise we could
-# just make a note of this and not run an editor after creation
-if ! hash "$EDITOR" &> /dev/null; then
-    err "$EDITOR: Does not exist"
-    exit 1
-fi
-
-# Make sure a template was chosen
-if [[ -n "$template" ]]; then
-    mk_template "$name" "$template"
-else
-    err "No template selected"
-    exit 1
-fi
-
-if [[ -n "$cover" ]]; then
-    mk_cover "$name" "$cover"
-else
-    warn "No image selected, using $placeholder"
-fi
-
-# Let the user edit the template, I'm not going to try run a CPP over this or any
-# other kind of templating engine as it just increases complexity, maybe...
-command "$EDITOR" "$bindir"/"$name"
diff --git a/taverner b/taverner
--- a/taverner
+++ b/taverner
@@ -1,135 +1,136 @@
 #!/usr/bin/env bash
 # taverner
 # Generate a dmenu for games on various platforms with associated cover images
-# and launch them based on custom shell scripts tailored for their needs
+# and launch them based on custom shell scripts tailored for their needs.
 
-# Includes
-# get_abs_dir, in_array, chk_dirs_exist, confirm, err, warn, debug, msg
-if ! source "$HOME"/.local/lib/libtavern; then
-    printf >&2 '[ERR] Failed to source %s\n' "$HOME"/.local/lib/libtavern
-    exit 1
-fi
-
-# Options
 shopt -s nullglob
 
-# Globals
-prefix="$HOME"/games
-bindir="$prefix"/bin
-cachedir="$prefix"/share/cache
-coverdir="$prefix"/share/covers
+readonly progn=taverner
+readonly datadir="${XDG_DATA_HOME:-$HOME/.local/share}"
+readonly prefix="$datadir"/taverner
+readonly bindir="$prefix"/bin
+readonly coverdir="$prefix"/covers
 
-# Check that the directories actually exist before attempting anything
-chk_dirs_exist "$prefix" "$bindir" "$coverdir" "$cachedir"
+# Main globals used throughout the code, unfortunately.
+declare -A titles
+declare -A covers
 
-dmenu_opts=(-i -w -ia top-gapless -is 200x250 
-            -fn 'Inconsolatazi4' -p 'Launch'
-            -nf '#a7a7a7' -nb '#1e1e1e'
-            -sf '#9b859d' -sb '#262626')
+read -r font < "${XDG_CONFIG_HOME:-$HOME/.config}"/dmenu/font
+readonly dmenu_opts=(
+    -i -w -ia top-gapless -is 200x250
+    -fn "$font" -p 'Launch'
+    -nf '#a7a7a7' -nb '#1e1e1e'
+    -sf '#9b859d' -sb '#262626'
+)
 
-# Generates a list of games along with associated cover and launcher script
-# paths
-gen_list() {
-    local bindir="${1:-$prefix/bin}"
-    local coverdir="${2:-$prefix/share/covers}"
-    local f title
+puts() {
+    printf -- "$1\n" "${@:2}"
+}
 
-    for f in "$bindir"/*; do
-        # Get the title from the script
-        while read -r title; do
-            # Look for '# Title:' and set the title based on what comes after
-            if [[ "$title" =~ '# Title: '?(.*) ]]; then
-                title="${BASH_REMATCH[1]}"
-                # Stop reading the file
-                break
-            fi
-        done < "$f"
+err() {
+    puts "$progn: $@" >&2
+}
 
-        # Check if the title exists else use the name of the script instead
-        # XXX Currently I don't check for duplicate titles at all, and I may
-        #     never do so in the current code.  What this means is that dmenu
-        #     will only ever show one and I have no way to tell which one that
-        #     will be.
-        if [[ -n "$title" ]]; then
-            printf '%s\n' "$title"
-        else
-            printf '%s\n' "${f##*/}"
-        fi
+title_in() {
+    local title
 
-        # Path to script which starts the program
-        printf '%s\n' "$f"
-
-        # Path to cover image with the same name as the script suffixed with
-        # .cover
-        if [[ -e "$coverdir"/"${f##*/}".cover ]]; then
-            printf '%s\n' "$coverdir"/"${f##*/}".cover
-        else
-            printf '%s\n' "$coverdir"/placeholder.cover
+    while read -r title; do
+        if [[ "$title" =~ '# Title: '?(.*) ]]; then
+            puts '%s' "${BASH_REMATCH[1]}"
+            break
         fi
     done
 }
 
-# (Re)generates the cache if new scripts are added otherwise does nothing
-# XXX This won't regenerate the cache if a title is changed in one of the
-#     launcher scripts, manual deletion of the cache is necessary
-chk_cache() {
-    local bindir="${1:-$prefix/bin}"
-    local cachedir="${2:-$prefix/share/cache}"
-    local nbins ncached
+generate_entry_data() {
+    #global bindir coverdir
+    local file filename title cover
 
-    # Get the number of files in $prefix/bin/ for comparison
-    nbins=("$bindir"/*); nbins="${#nbins[@]}"
+    for file in "$bindir"/*; do
+        if [[ -e "$file" ]]; then
+            title="$(title_in < "$file")"
+        fi
 
-    # Make sure we have something to generate before attempting to generate
-    if ((nbins == 0)); then
-        err "Couldn't generate list as no launchers exist in $bindir"
-        exit 1
-    fi
+        filename="${file##*/}"
 
-    # If the cache.db doesn't exist then neither should num.db
-    # Then make sure the num.db exists before trying to read it
-    if [[ ! -e "$cachedir"/cache.db ]]; then
-        rm -- "$cachedir"/num.db &> /dev/null
-    elif [[ -e "$cachedir"/num.db ]]; then
-        read -r ncached < "$cachedir"/num.db
-    fi
+        # Use the filename if no title could be found.
+        if [[ -z "$title" ]]; then
+            title="$filename"
+        fi
 
-    # Check if the number of binaries don't match what we have cached, then
-    # (re)generate the cache.db and num.db
-    if ((ncached != nbins)); then
-        #debug "${FUNCNAME[0]}: nbins($nbins) > ncached($ncached) should be true"
-        gen_list > "$cachedir"/cache.db
-        printf '%s\n' "$nbins" > "$cachedir"/num.db
+        # If a matching cover image isn't found use a placeholder instead.
+        if [[ -e "$coverdir"/"$filename" ]]; then
+            cover="$coverdir"/"$filename"
+        else
+            cover="$coverdir"/placeholder
+        fi
+
+        puts '%s' "$title"
+        puts '%s' "$file"
+        puts '%s' "$cover"
+    done
+}
+
+create_dmenu() {
+    #global titles covers
+    local key
+
+    for key in "${!titles[@]}"; do
+        puts 'IMG:%s\t%s' "${covers[$key]}" "$key"
+    done
+}
+
+get_user_picks() {
+    #global dmenu_opts
+    create_dmenu | sort | dmenu "${dmenu_opts[@]}"
+}
+
+launch() {
+    local err
+    local executable="$1"
+
+    if ! err="$(command -- "$executable")"; then
+        err '%s' "${err:-$executable}"
     fi
 }
 
-# Check the cache before continuing
-# XXX There's not much reason to make this a function simply to run it once, but
-#     it lets me use more local variables
-chk_cache
+populate_arrays() {
+    #global titles covers
 
-# Parse the list into two arrays.  We keep a consistent key so we can access
-# the correct corresonding information for both lookups
-declare -A titles
-declare -A covers
+    # Parse the list into two arrays.  We keep a consistent key so we can access
+    # the correct corresonding information for both lookups.
+    while {
+        read -r title
+        read -r entry
+        read -r cover
+    } do
+        titles["$title"]="$entry"
+        covers["$title"]="$cover"
+    done
+}
 
-while {
-    read -r title
-    read -r bin
-    read -r cover
-} do
-    titles["$title"]="$bin"
-    covers["$title"]="$cover"
-done < "$cachedir"/cache.db
+process_results() {
+    #global titles
+    local pick entry
 
-# Print the two arrays in a compliant manner for dmenu to consume before
-# executing the results
-if sel=$(
-    for k in "${!titles[@]}"; do
-        printf "IMG:%s\t%s\n" "${covers[$k]}" "$k"
-    done | sort | dmenu "${dmenu_opts[@]}"
-); then
-    command "${titles[$sel]}"
-else
-    exit 0
+    while read -r pick; do
+        if [[ -n "${titles[$pick]}" ]]; then
+            game="${titles[$pick]}"
+        else
+            err '%s: Cannot find associated launcher.' "$pick"
+            exit 1
+        fi
+
+        launch "$entry" &
+    done
+}
+
+mkdir -p "$datadir" "$bindir" "$coverdir"
+
+populate_arrays < <(generate_entry_data)
+
+results="$(get_user_picks)"
+
+if [[ -n "$results" ]]; then
+    process_results <<< "$results"
 fi
